name: Check and create tag
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  new_version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Get version number
        run: |
          echo "VSM_VER=v$(cat vsmask/_metadata.py | sed -nr "s/__version__ = '(.*)'/\1/p")" >> $GITHUB_ENV

      - name: Check if version exists
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        uses: mukunku/tag-exists-action@v1.1.0
        id: tagcheck
        with:
          tag: ${{ env.VSM_VER }}

      - name: Make tag
        uses: actions/github-script@v6
        if: steps.tagcheck.outputs.exists == 'false'
        with:
          github-token: ${{ secrets.WORKFLOW_TOKEN }}
          script: |
            github.rest.git.createRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: `refs/tags/${process.env.VSM_VER}`,
              sha: context.sha
            })

      - name: Fallback
        if: steps.tagcheck.outputs.exists == 'true'
        run: echo "Nothing to see here, move along citizen"